name: ci
on: [push]
jobs:
    ui:
      runs-on: ubuntu-latest
      container:
        image: node:lts
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - run: |
            cd ui
            npm install
            npm run test:unit
            npm run build
            
    infrastructure:
      runs-on: ubuntu-latest
      container:
        image: node:lts
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - run: |
            mkdir -p ui/dist
            cd infrastructure
            npm install
            npm run test
            npm run build